include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: ignore
    unused_local_variable: warning
    unused_import: error

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unsafe_html
